---
- name: Create AMI
  ec2_ami:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: '{{ region }}'
    instance_id: "{{ ec2_out.instances.0.id }}"
    wait: yes
    name: 'new_ami-{{ ansible_date_time.epoch }}'
  register: ami_image

- name: New AMI
  debug:
    var: ami_image
